// CONSTANT_CASE on purpose — see biome.json overrides.
export const ApiEndpoints = {
  LOGIN: "/api/login",
  LOGOUT: "/api/logout",
  REFRESH_TOKEN: "/api/auth/token/refresh",
  WHOAMI: "/api/whoami",
  ACCOUNT: "/api/account",
  ACCOUNT_POUCH: "/api/account/pouch",
  ITEMS: "/api/items",
  ITEMS_TRASH: "/api/items/trash",
  ITEM: (id: number) => `/api/items/${id}`,
  ITEM_MOVE: (id: number) => `/api/items/${id}/move`,
  ITEM_RESTORE: (id: number) => `/api/items/${id}/restore`,
  ITEM_FILES: "/api/items/files",
  ITEM_PHOTOS: "/api/items/photos",
  ITEM_URLS: "/api/items/urls",
  ITEM_NOTES: "/api/items/notes",
  ITEM_NOTE: (id: number) => `/api/items/${id}/note`,
  ITEM_THUMBNAIL_LINK: (id: number) => `/api/items/${id}/thumbnail-link`,
  ITEM_DOWNLOAD_LINK: (id: number) => `/api/items/${id}/download-link`,
  ITEM_TAGS: (id: number) => `/api/items/${id}/tags`,
  ITEM_FAVORITE: (id: number) => `/api/items/${id}/favorite`,
  ITEM_FILE: (id: number) => `/api/items/${id}/file`,
  ITEM_VERSIONS: (id: number) => `/api/items/${id}/versions`,
  ITEM_VERSION_DOWNLOAD_LINK: (id: number, version: number) => `/api/items/${id}/versions/${version}/download-link`,
  ITEM_PUBLIC_LINK: (id: number) => `/api/items/${id}/public-link`,
  ITEM_UNLOCK: (id: number) => `/api/items/${id}/unlock`,
  ITEM_ACCESS_KEY: (id: number) => `/api/items/${id}/access-key`,
  CATEGORIES: "/api/categories",
  CATEGORY: (id: number) => `/api/categories/${id}`,
  CATEGORY_RENAME: (id: number) => `/api/categories/${id}/rename`,
  CATEGORY_MOVE: (id: number) => `/api/categories/${id}/move`,
  CATEGORY_UNLOCK: (id: number) => `/api/categories/${id}/unlock`,
  CATEGORY_ACCESS_KEY: (id: number) => `/api/categories/${id}/access-key`,
  CATEGORY_EXPORT: (id: number) => `/api/categories/${id}/export`,
  CATEGORY_EXPORT_TOKEN: (id: number) => `/api/categories/${id}/export-token`,
  TAGS: "/api/tags",
  TAGS_ALL: "/api/tags/all",
  TAG: (id: number) => `/api/tags/${id}`,
  TAG_RENAME: (id: number) => `/api/tags/${id}/rename`,
  ADMIN_STORAGE: "/api/admin/storage",
  ADMIN_STORAGE_LIMIT: (type: string) => `/api/admin/storage/limits/${type}`,
  ADMIN_GC_RUN: "/api/admin/gc/run",
  ADMIN_GC_RUNS: "/api/admin/gc/runs",
  ADMIN_AUDIT_LOG: "/api/admin/audit-log",
  ADMIN_ITEMS_EXPIRING_SOON: "/api/admin/items/expiring-soon",
  ADMIN_ITEMS_EXTEND: "/api/admin/items/extend",
  ADMIN_BACKUP: "/api/admin/backup",
  ADMIN_USERS: "/api/admin/users",
  ADMIN_USER: (id: number) => `/api/admin/users/${id}`,
  ADMIN_USER_ROLE: (id: number) => `/api/admin/users/${id}/role`,
  ADMIN_USER_ENABLED: (id: number) => `/api/admin/users/${id}/enabled`,
  ADMIN_USER_RESET_PASSWORD: (id: number) => `/api/admin/users/${id}/reset-password`,
  ADMIN_POUCHES: "/api/admin/pouches",
  ADMIN_ITEMS: "/api/admin/items",
  ADMIN_ITEM: (id: number) => `/api/admin/items/${id}`,
  ADMIN_TECHNICAL_BREAK: "/api/admin/technical-break",
} as const;

// A 401 here must not trigger a refresh-and-retry (wrong credentials / dead refresh token).
export const NO_REFRESH_ENDPOINTS: readonly string[] = [ApiEndpoints.LOGIN, ApiEndpoints.REFRESH_TOKEN];
