<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Part 10: the admin panel's own tables — audit_log (append-only event log),
 * gc_run_log (one row per GC cycle), storage_limit (admin overrides of the
 * built-in per-type upload size limits). None of these reference item/
 * category by foreign key on purpose: an audit/GC-log row must survive the
 * resource it refers to being deleted (that's often exactly what it's
 * recording), and storage_limit's "resource" is just an ItemType value, not
 * a row anywhere.
 */
final class Version20260831160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'audit_log, gc_run_log, storage_limit tables (Part 10: admin panel)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE audit_log (
                audit_log_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                action VARCHAR(32) NOT NULL,
                resource_type VARCHAR(32) NOT NULL,
                resource_id INT NOT NULL,
                user_id INT DEFAULT NULL,
                user_email VARCHAR(255) DEFAULT NULL,
                ip VARCHAR(45) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (audit_log_id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_audit_log_created_at ON audit_log (created_at)');

        $this->addSql(<<<'SQL'
            CREATE TABLE gc_run_log (
                gc_run_log_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trigger VARCHAR(16) NOT NULL,
                expired_count INT NOT NULL,
                purged_count INT NOT NULL,
                run_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (gc_run_log_id)
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE storage_limit (
                type VARCHAR(32) NOT NULL,
                max_size_bytes BIGINT NOT NULL,
                PRIMARY KEY (type)
            )
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE storage_limit');
        $this->addSql('DROP TABLE gc_run_log');
        $this->addSql('DROP TABLE audit_log');
    }
}
