<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260902101954 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add technical_break table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE technical_break (technical_break_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, active BOOLEAN NOT NULL, message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (technical_break_id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE technical_break');
    }
}
