<?php

declare(strict_types = 1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * New `pouch` table + `category.pouch_id`/`user.pouch_id`, both NOT NULL.
 * Hand-written, not `make:migration`'s raw diff: a NOT NULL FK on tables that
 * already have rows needs a backfill in between, which the auto-diff can't
 * generate — one default pouch is created here and every existing
 * user/category is assigned to it.
 *
 * The auto-generated diff this was based on also wanted to drop
 * `item.search_vector`/its index and rename two unrelated indexes — that's
 * Doctrine's schema comparator not understanding a DB-generated column
 * (unmapped in the Item entity on purpose), not real drift, so it's left out.
 */
final class Version20260831190537 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Część 16: pouch table + category.pouch_id/user.pouch_id (NOT NULL), backfilled to one default pouch';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pouch (pouch_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (pouch_id))');

        $this->addSql('ALTER TABLE category ADD pouch_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD pouch_id INT DEFAULT NULL');

        $this->addSql("INSERT INTO pouch (name, created_at) VALUES ('Domyślny pouch', NOW())");
        $this->addSql('UPDATE category SET pouch_id = (SELECT pouch_id FROM pouch ORDER BY pouch_id LIMIT 1) WHERE pouch_id IS NULL');
        $this->addSql('UPDATE "user" SET pouch_id = (SELECT pouch_id FROM pouch ORDER BY pouch_id LIMIT 1) WHERE pouch_id IS NULL');

        $this->addSql('ALTER TABLE category ALTER pouch_id SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER pouch_id SET NOT NULL');

        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1566320D4 FOREIGN KEY (pouch_id) REFERENCES pouch (pouch_id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_64C19C1566320D4 ON category (pouch_id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649566320D4 FOREIGN KEY (pouch_id) REFERENCES pouch (pouch_id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8D93D649566320D4 ON "user" (pouch_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1566320D4');
        $this->addSql('DROP INDEX IDX_64C19C1566320D4');
        $this->addSql('ALTER TABLE category DROP pouch_id');

        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649566320D4');
        $this->addSql('DROP INDEX IDX_8D93D649566320D4');
        $this->addSql('ALTER TABLE "user" DROP pouch_id');

        $this->addSql('DROP TABLE pouch');
    }
}
