<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260830143948 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE item ADD processing_status VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE item ADD processing_error TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE item ADD thumbnail_storage_key VARCHAR(512) DEFAULT NULL');
        $this->addSql('ALTER TABLE item ADD url VARCHAR(2048) DEFAULT NULL');
        $this->addSql('ALTER TABLE item ADD page_title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE item ADD page_description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE item ADD extracted_text TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE item ALTER original_filename DROP NOT NULL');
        $this->addSql('ALTER TABLE item ALTER mime_type DROP NOT NULL');
        $this->addSql('ALTER TABLE item ALTER size DROP NOT NULL');
        $this->addSql('ALTER TABLE item ALTER storage_key DROP NOT NULL');
        $this->addSql('ALTER TABLE item ALTER content_hash DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F1B251E5CA9667B ON item (thumbnail_storage_key)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP INDEX UNIQ_1F1B251E5CA9667B');
        $this->addSql('ALTER TABLE item DROP processing_status');
        $this->addSql('ALTER TABLE item DROP processing_error');
        $this->addSql('ALTER TABLE item DROP thumbnail_storage_key');
        $this->addSql('ALTER TABLE item DROP url');
        $this->addSql('ALTER TABLE item DROP page_title');
        $this->addSql('ALTER TABLE item DROP page_description');
        $this->addSql('ALTER TABLE item DROP extracted_text');
        $this->addSql('ALTER TABLE item ALTER original_filename SET NOT NULL');
        $this->addSql('ALTER TABLE item ALTER mime_type SET NOT NULL');
        $this->addSql('ALTER TABLE item ALTER size SET NOT NULL');
        $this->addSql('ALTER TABLE item ALTER storage_key SET NOT NULL');
        $this->addSql('ALTER TABLE item ALTER content_hash SET NOT NULL');
    }
}
