<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Part 6: tags (M:N), favorites, and full-text search.
 *
 * Hand-written rather than make:migration-generated: `tag`/`item_tag` and
 * `is_favorite` could have come from an entity diff, but `search_vector` is a
 * Postgres GENERATED STORED column (to_tsvector over the item's own text
 * fields) with no Doctrine DBAL type, so the whole migration is raw SQL for
 * consistency — see Item::class and ItemRepository::searchMatchingIds().
 */
final class Version20260830210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Tags (M:N), item.is_favorite, item.search_vector (generated tsvector + GIN index)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tag (tag_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (tag_id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tag_name ON tag (name)');

        $this->addSql('CREATE TABLE item_tag (item_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (item_id, tag_id))');
        $this->addSql('CREATE INDEX idx_item_tag_tag_id ON item_tag (tag_id)');
        $this->addSql('ALTER TABLE item_tag ADD CONSTRAINT FK_item_tag_item FOREIGN KEY (item_id) REFERENCES item (item_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_tag ADD CONSTRAINT FK_item_tag_tag FOREIGN KEY (tag_id) REFERENCES tag (tag_id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE item ADD is_favorite BOOLEAN NOT NULL DEFAULT false');

        $this->addSql(<<<'SQL'
            ALTER TABLE item ADD search_vector tsvector GENERATED ALWAYS AS (
                to_tsvector('simple',
                    coalesce(name, '') || ' ' ||
                    coalesce(note_content, '') || ' ' ||
                    coalesce(extracted_text, '') || ' ' ||
                    coalesce(page_title, '') || ' ' ||
                    coalesce(page_description, '')
                )
            ) STORED
            SQL);
        $this->addSql('CREATE INDEX idx_item_search_vector ON item USING GIN (search_vector)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX idx_item_search_vector');
        $this->addSql('ALTER TABLE item DROP search_vector');
        $this->addSql('ALTER TABLE item DROP is_favorite');
        $this->addSql('DROP TABLE item_tag');
        $this->addSql('DROP TABLE tag');
    }
}
