<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Closes the duplicate-upload race (check-then-insert on content_hash):
 * two concurrent uploads of the same content could both pass the app-level
 * SELECT before either flushed. A plain unique index isn't right here —
 * trashed items keep their content_hash but shouldn't block a fresh upload
 * of the same content — so this is a *partial* unique index (Doctrine's
 * attributes can't express a WHERE clause), hand-written rather than
 * generated by make:migration.
 */
final class Version20260830190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Partial unique index on item.content_hash for active (non-trashed) items';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP INDEX idx_item_content_hash');
        $this->addSql('CREATE UNIQUE INDEX uniq_item_content_hash_active ON item (content_hash) WHERE (trashed_at IS NULL AND content_hash IS NOT NULL)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX uniq_item_content_hash_active');
        $this->addSql('CREATE INDEX idx_item_content_hash ON item (content_hash)');
    }
}
