<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Part 8: file versioning. item.* is untouched — it always holds the
 * *current* version (same id/URL, per the product doc) — this is purely the
 * history of what it used to hold, one row per version an item was
 * overwritten out of. See Entity/ItemVersion.php.
 */
final class Version20260831140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'item_version table (Part 8: file versioning)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE item_version (
                item_version_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                item_id INT NOT NULL,
                version INT NOT NULL,
                original_filename VARCHAR(255) NOT NULL,
                mime_type VARCHAR(255) NOT NULL,
                size BIGINT NOT NULL,
                storage_key VARCHAR(512) NOT NULL,
                content_hash VARCHAR(64) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (item_version_id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_item_version ON item_version (item_id, version)');
        $this->addSql('CREATE UNIQUE INDEX uniq_item_version_storage_key ON item_version (storage_key)');
        $this->addSql('ALTER TABLE item_version ADD CONSTRAINT FK_item_version_item FOREIGN KEY (item_id) REFERENCES item (item_id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE item_version');
    }
}
